[package]
name = "trainbuttons"
version = "0.1.0"
edition = "2021"

[dependencies]
bitmacros = { path = "../bitmacros" }
cortex-m = { version = "0.7" }
cortex-m-rt = { version = "0.7" }
stm32g0b0 = { path = "../stm32g0b0", features = ["rt"] }
